[serieson_free]
title = "[시리즈온] 이주의 무료영화"
url = "https://serieson.naver.com/movie/freeMovieList.nhn"
entrySelector = "ul.lst_freemovie li"
titleSelector = "strong.freemovie_title"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "span.freemovie_deadline"

[serieson_sale]
title = "[시리즈온] 할인 영화관"
url = "https://serieson.naver.com/movie/categoryList.nhn?categoryCode=300003"
entrySelector = "ul.lst_thum.v1 li"
titleSelector = "a strong"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "strong.payment"
waitUntil = "networkidle"

[serieson_sale1000]
title = "[시리즈온] 천원관"
url = "https://serieson.naver.com/movie/categoryList.nhn?categoryCode=300007"
entrySelector = "ul.lst_thum.v1 li"
titleSelector = "a strong"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "p.price2.v2 em"
waitUntil = "networkidle"

[serieson_barrierfree]
title = "[시리즈온] 가치봄 영화관"
url = "https://serieson.naver.com/movie/categoryList.nhn?categoryCode=300009&tagCode=200000"
entrySelector = "ul.lst_thum.v1 li"
titleSelector = "a strong"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "p.price2.v2"
waitUntil = "networkidle"

[daummovie_netflix_c]
title = "[다음영화] 넷플릭스 ─ 종료예정"
url = "https://movie.daum.net/premovie/netflix?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_netflix_y]
title = "[다음영화] 넷플릭스 ─ 공개예정"
url = "https://movie.daum.net/premovie/netflix?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_watcha_c]
title = "[다음영화] 왓챠 ─ 종료예정"
url = "https://movie.daum.net/premovie/watcha?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_watcha_y]
title = "[다음영화] 왓챠 ─ 공개예정"
url = "https://movie.daum.net/premovie/watcha?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_kakaopage_c]
title = "[다음영화] 카카오페이지 ─ 종료예정"
url = "https://movie.daum.net/premovie/kakaopage?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_kakaopage_y]
title = "[다음영화] 카카오페이지 ─ 공개예정"
url = "https://movie.daum.net/premovie/kakaopage?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"
