[daummovie_netflix_c]
title = "[다음영화] 넷플릭스 ─ 종료예정"
url = "https://movie.daum.net/premovie/netflix?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[daummovie_netflix_y]
title = "[다음영화] 넷플릭스 ─ 공개예정"
url = "https://movie.daum.net/premovie/netflix?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"